shared:
  model_num: 1
  max_epoch: 20 # # #
  enable_dict:
    acc: true
    loss: true
    reward: false
    model: true
    opt: true
    epoch: true
    val: true
    test: true
    data: false ###
    lr: true
  quick_calc: true
monitor:
  classArgs:
    report:
      intermediate_default: val_acc
      final_default: val_acc
tuner:
  classArgs:
    basic:
      optimize_mode: maximize
      algorithm_name: random
      rule_name_list: [ "at","dd" ] #
    rectify:
      k: 0.5
      b: 0.5
      base_probability: 0.1
      max_probability: 0.95
      start_duration_float: 0.9 ####
      end_duration_float: 1.0
      same_retry_maximum: 10
      retained_parameter_list: [ "bn_layer", "act_func", "grad_clip", "init", "opt", "batch_size", "lr", "epoch" ]
    parallel:
      parallel_optimize: false
      constant_liar_type: min
#    reproduce:
#      experiment_id: eeeee
assessor:
  classArgs:
    basic:
      maximize_metric_name_list: [ "acc","sc_metric" ]
      minimize_metric_name_list: [ "loss","veg_metric","dr_metric","ol_metric" ] # remove: val_loss add: loss acc
    compare:
      k: 0
      b: 0.5
      max_percentile: 90
      start_step_float: 0.5 ###### pre:0.0
      end_step_float: 1.0 ###### pre:0.75
      step_size: 1 # pre:"median"
      metric_demarcation_num: 10
      comparable_trial_minimum: 10 ###
    diagnose:
      beta1: 0.001
      beta3: 70
      gamma: 0.7
      zeta: 0.03
      delta: -0.01  # okkk
      window_size_float: 0.25
      window_size_min: 5
inspector:
  classArgs:
    basic:
      start_step_float: 0 ###### pre:0.15
      rule_name_list: [ "at","dd" ] # del "wd": var&mean aggressive & similar to ani&lnd
      continuous_trigger_count: 2 ####
    diagnose:
      alpha1: 0
      alpha2: 0
      alpha3: 0
      beta1: 0.001
      beta2: 0.0001
      beta3: 70
      gamma: 0.7
      delta: 0.01
      zeta: 0.03
      theta: 0.9
      eta: 0.2
      # dd
      dd_max_threshold: 10
      dd_min_threshold: 0.00001
      dd_threshold_VG: 1.e-7
      # wd dd
      window_size_float: 0.25
      window_size_min: 5