shared:
  max_epoch: 20 #
  enable_dict:
    acc: true
    loss: true
    model: true
    val: true
    test: true
  quick_calc: true
monitor:
  class_args:
    report:
      intermediate_default: val_acc
      final_default: val_acc
tuner:
  class_args:
    reproduce:
      enable: false
      experiment_id: eeeee
assessor:
  class_args:
    basic:
      start_step_float: 0.0
      end_step_float: 0.5
      symptom_name_list: [ "VG","EG","DR","SC","HO","NMG" ]
    compare:
      cmp_mode: minimize
      cmp_percent: 10
      cmp_metric_name: "train_loss" # del: "train_acc"
      min_cmp_num: 10
    diagnose:
      p_eg1: 10
      p_eg2: 1.e+5 ## ok
      p_eg3: 10
      p_vg1: 1.e-7
      p_vg2: 0.01
      p_vg3: 0.1
      p_dr1: 0.1
      p_dr2: -1
      p_sc1: -1
      p_sc2: 0
      p_ho1: -1
      p_ho2: 0.01 # okk
      p_nmg1: -1
      p_nmg2: 0
      wd_ho: 0.25
      wd_nmg: 0.25


















