shared:
  max_epoch: 20 #
  enable_dict:
    acc: true
    loss: true
    model: true
    val: true
    test: true
  quick_calc: true
monitor:
  class_args:
    report:
      intermediate_default: val_acc
      final_default: val_acc
tuner:
  class_args:
    reproduce:
      enable: false
      experiment_id: eeeee
assessor:
  class_args:
    basic:
      start_step_float: 0.0
      end_step_float: 0.5
      rule_name_list: [ "VG","EG","DR","SC","HO","NG" ]
    compare:
      top_percent: 90
      metric_name_list: [ "train_acc","train_loss" ]
      comparable_trial_minimum: 10
    diagnose:
      p_vg1: 1.e-7
      p_vg3: 0.1
      p_vg2: 0.01
      p_eg1: 10
      p_eg2: 1000
      p_eg3: 100
      p_dr1: 0.5
      p_dr2: 0.5
      p_ho1: 0.1
      p_ho2: 0.1
      p_ng1: 0.1
      p_ng2: 0.1
      wd: 0.25
# diagnose_params = namedtuple("diagnose_params", {
#    "p_vg1", "p_vg2", "p_vg3",
#    "p_eg1", "p_eg2", "p_eg3",
#    "p_dr1", "p_dr2",
#    "p_ho1", "p_ho2",
#    "p_ng1", "p_ng2",
#    "wd"
#})


















