experiment_name: "shortterm_ett_autoformer_raw_random"
searchSpaceFile: space.json


trial_command: python3 trial.py
trial_code_directory: .

trial_concurrency: 4
maxExperimentDuration: 6h ####
training_service:
  platform: local
  useActiveGpu: false
trialGpuNumber: 1

tuner:
  name: random
  class_args:
    optimize_mode: minimize






