experiment_name: "shortterm_ett_autoformer_our_random"
searchSpaceFile: space.json


trial_command: python3 trial.py
trial_code_directory: .

trial_concurrency: 4
maxExperimentDuration: 6h ####
training_service:
  platform: local
  useActiveGpu: false
trialGpuNumber: 1

advisor:
  codeDirectory: ../../new_package ###
  className: atdd_advisor.ATDDAdvisor
  classArgs:
    shared:
      max_epoch: 20
      enable_dict:
        acc: false
    monitor: default
    tuner:
      name: random
      class_args:
        optimize_mode: minimize
    assessor: default







